### ISSUE TITLE
iPhone 6 第二个 tabBarItem 的 导航栏头视图错位

### ISSUE THREAD

**Issue by ChengLuffy** [Sepicat/Sepikit.issue#12]
从其他 item点到第二个会出现这个问题

**Comment by Desgard** [comment]
OK 已经在修复，这个是 XLPagerTabStrip 三方库的已知问题。多谢！

**Comment by qiuncheng** [comment]
准确说，在第二个 tab 页处于 Watching 下，第四个 tab 页处于 Developers 页，标题都会向右边偏移。

**Comment by Desgard** [comment]
Fixed in Version 1.0.1
