### ISSUE TITLE
v1.0.1 Trending 页检索行为导致崩溃

### ISSUE THREAD

**Issue by ChengLuffy** [Sepicat/Sepikit.issue#21]
输入 swift 选 day 然后应用崩溃

From: iOS 11.3, iPhone 6

**Comment by ChengLuffy** [comment]
[Sepicat-2018-03-21-093914.ips.zip](https://github.com/Sepicat/Sepikit.issue/files/1831804/Sepicat-2018-03-21-093914.ips.zip)

附赠崩溃日志一枚。

**Comment by Desgard** [comment]
@ChengLuffy 感谢
