### ISSUE TITLE
filter doesn't work

### ISSUE THREAD

**Issue by gyh1621** [Sepicat/Sepikit.issue#6]
filter in developer not work

**Comment by gyh1621** [comment]
早上 repositories 页面刷新不出来，然后我以为 filter 能过滤 developer 页面，现在看来是过滤 repositories 页面的？
在 repositories 页面指定语言时间段筛选后会自动刷新出筛选结果，但是在 filter 里面不改语言更改时间段后页面不会刷新筛选结果

**Comment by Desgard** [comment]
Fixed in Version 1.0.0
